#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnotify
Version  : 0.7.7
Release  : 4
URL      : http://ftp.gnome.org/pub/gnome/sources/libnotify/0.7/libnotify-0.7.7.tar.xz
Source0  : http://ftp.gnome.org/pub/gnome/sources/libnotify/0.7/libnotify-0.7.7.tar.xz
Summary  : Notifications Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libnotify-bin
Requires: libnotify-lib
Requires: libnotify-doc
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : xmlto

%description


%package bin
Summary: bin components for the libnotify package.
Group: Binaries

%description bin
bin components for the libnotify package.


%package dev
Summary: dev components for the libnotify package.
Group: Development
Requires: libnotify-lib
Requires: libnotify-bin
Provides: libnotify-devel

%description dev
dev components for the libnotify package.


%package doc
Summary: doc components for the libnotify package.
Group: Documentation

%description doc
doc components for the libnotify package.


%package lib
Summary: lib components for the libnotify package.
Group: Libraries

%description lib
lib components for the libnotify package.


%prep
%setup -q -n libnotify-0.7.7

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/notify-send

%files dev
%defattr(-,root,root,-)
/usr/include/libnotify/notification.h
/usr/include/libnotify/notify-enum-types.h
/usr/include/libnotify/notify-features.h
/usr/include/libnotify/notify.h
/usr/lib64/*.so
/usr/lib64/girepository-1.0/Notify-0.7.typelib
/usr/lib64/pkgconfig/*.pc
/usr/share/gir-1.0/*.gir

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/libnotify/NotifyNotification.html
/usr/share/gtk-doc/html/libnotify/annotation-glossary.html
/usr/share/gtk-doc/html/libnotify/api-index-deprecated.html
/usr/share/gtk-doc/html/libnotify/api-index-full.html
/usr/share/gtk-doc/html/libnotify/ch01.html
/usr/share/gtk-doc/html/libnotify/home.png
/usr/share/gtk-doc/html/libnotify/index.html
/usr/share/gtk-doc/html/libnotify/left-insensitive.png
/usr/share/gtk-doc/html/libnotify/left.png
/usr/share/gtk-doc/html/libnotify/libnotify-notify.html
/usr/share/gtk-doc/html/libnotify/libnotify.devhelp2
/usr/share/gtk-doc/html/libnotify/right-insensitive.png
/usr/share/gtk-doc/html/libnotify/right.png
/usr/share/gtk-doc/html/libnotify/style.css
/usr/share/gtk-doc/html/libnotify/up-insensitive.png
/usr/share/gtk-doc/html/libnotify/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
